### PR TITLE
Fix some issues with double buffering, add some specific tests to guard against regression

### LINKED ISSUE #799: net.openhft.chronicle.queue.impl.single.TestMethodWriterWithThreads for doubleBuffer=true
It is working now for doubleBuffer=false

### PR DESCRIPTION
**Pull request by nicktindall**
Fixed #799

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/queue/impl/single/StoreAppender.java [hunk 1]
```diff
@@ -356,17 +356,19 @@ public DocumentContext writingDocument(final boolean metaData) {
 
             // sets the writeLimit based on the safeLength
             openContext(metaData, safeLength);
+
+            // there is nothing to read.
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/queue/impl/single/StoreAppender.java]: TODO: Still need to improve this comment

File: src/main/java/net/openhft/chronicle/queue/impl/single/StoreAppender.java [hunk 2]
```diff
@@ -356,17 +356,19 @@ public DocumentContext writingDocument(final boolean metaData) {
...
+
         return writeContext;
     }
 
     @Override
     public DocumentContext acquireWritingDocument(boolean metaData) {
         if (!DISABLE_THREAD_SAFETY)
             this.threadSafetyCheck(true);
-        if (wire != null && writeContext.isOpen() && writeContext.chainedElement())
+        if (writeContext.wire != null && writeContext.isOpen() && writeContext.chainedElement())
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/queue/impl/single/StoreAppender.java:371]: This broke the chained `methodWriter` writes when double buffering. It mean `count` never got to zero so the buffer was never written back.

File: src/main/java/net/openhft/chronicle/queue/impl/single/StoreAppender.java [hunk 3]
```diff
@@ -834,6 +836,7 @@ public void close(boolean unlock) {
                     if (buffered) {
                         writeBytes(wire.bytes());
                         unlock = false;
+                        wire.clear();
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/queue/impl/single/StoreAppender.java:839]: When the buffer was used the second time, the previous calls were still in it.

File: src/test/java/net/openhft/chronicle/queue/impl/single/RollCycleMultiThreadStressDoubleBufferTest.java [hunk 4]
```diff
@@ -1,19 +1,93 @@
...
+                    if (unexpectedValues.contains(expected)) {
+                        unexpectedValues.remove(expected);
+                    } else {
+                        skippedValue.add(expected);
+                    }
+                    if (skippedValue.contains(v)) {
+                        skippedValue.remove(v);
+                    } else {
+                        unexpectedValues.add(v);
+                    }
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/queue/impl/single/RollCycleMultiThreadStressDoubleBufferTest.java:72]: I'm sure there's a cleverer/more efficient way to track this... I'll come back to it.

File: src/test/java/net/openhft/chronicle/queue/impl/single/RollCycleMultiThreadStressTest.java [hunk 5]
```diff
@@ -477,6 +520,10 @@ private int write(ExcerptAppender appender) {
             try (DocumentContext writingDocument = appender.writingDocument()) {
                 final long documentAcquireTimestamp = System.nanoTime();
                 value = wrote.getAndIncrement();
+                if (value >= expectedNumberOfMessages) {
+                    writingDocument.rollbackOnClose();
+                    return value;
+                }
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/queue/impl/single/RollCycleMultiThreadStressTest.java:533]: I needed to do this because threads can open `DocumentContext`s concurrently when double buffering is enabled, so in those circumstances they'd sometimes write more than `expectedNumberOfMessages`

Comment (nicktindall) [reply src/test/java/net/openhft/chronicle/queue/impl/single/RollCycleMultiThreadStressTest.java:533]: Combine that with being potentially out of order and it becomes very hard to check on the reader side.

File: src/main/java/net/openhft/chronicle/queue/impl/single/StoreAppender.java [hunk 6]
```diff
@@ -856,12 +859,17 @@ public void close(boolean unlock) {
...
+                assert wire != StoreAppender.this.wire;
+                wire.clear();
+            } else {
+                // zero out all contents...
+                for (long i = positionOfHeader; i <= wire.bytes().writePosition(); i++)
+                    wire.bytes().writeByte(i, (byte) 0);
+                long lastPosition = StoreAppender.this.lastPosition;
+                position0(lastPosition, lastPosition);
+                ((AbstractWire) wire).forceNotInsideHeader();
+            }
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/queue/impl/single/StoreAppender.java:872]: This isn't pretty, but it gets the job done. Previously `doRollback` assumed `StoreAppenderContext.wire == StoreAppender.wire`

File: src/test/java/net/openhft/chronicle/queue/impl/single/RollCycleMultiThreadStressTest.java (hunk 5 above)
Comment (JerryShea) [reply src/test/java/net/openhft/chronicle/queue/impl/single/RollCycleMultiThreadStressTest.java:533]: maybe add a comment to that code explaining why?

**Review by JerryShea — APPROVED** [review]
