### PR TITLE
Fix for skipped roll cycle due to bad header. Fixes #1509

### LINKED ISSUE #1509: Tailers can skip unacquirable cycles
When reading through a queue, if a cycle is encountered with an incomplete or invalid header, a tailer will pause (for, by default, 10s) waiting for the header to become valid.

The assumption is it has encountered a new roll cycle in the process of being initialised, and the actual wait time will be much shorter.

If a process dies abruptly while initialising a roll cycle it can leave a bad roll cycle that will hold up all readers/appenders for the full 10s, before an appender will go in and rename the file and replace it with a valid one.

[Some work was done recently](https://github.com/OpenHFT/Chronicle-Queue/pull/1368) to better handle missing roll cycles, when a Tailer failed to acquire a cycle it was assumed to be due to the file being missing, so it would skip forward to the next one.

If a Tailer fails to acquire a cycle because it's partly initialised that is indistinguishable from it failing to acquire one because it's missing from disk. In the former case, it's possible that while it was waiting 10s for the header to be complted, that roll cycle was replaced, populated and the following roll cycle was created (most likely in a replication scenario or one with very short roll cycles). In this scenario the tailer would skip over the replacement cycle and miss a bunch of excerpts.

This caused flappiness in UngracefulShutdownTest.

### PR DESCRIPTION
**Pull request by nicktindall**
Fixesd #1509

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/queue/impl/single/StoreTailer.java [hunk 1]
```diff
@@ -530,16 +530,15 @@ private long nextIndexWithNextAvailableCycle0(final int cycle) {
...
-                    }
+                final int nextCycle0 = queue.nextCycle(this.cycle, direction);
+                if (nextCycle0 == -1)
+                    return Long.MIN_VALUE;
+
+                if (cycle(nextCycle0)) {
+                    nextIndex = nextIndexWithinFoundCycle(nextCycle0);
+                } else {
+                    queue.refreshDirectoryListing();
+                    return Long.MIN_VALUE;
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/queue/impl/single/StoreTailer.java:541]: The failure to acquire a cycle here is not necessarily due to the cycle not existing. When it occurs, we have to return that no next cycle was found, and force-refresh the directory listing to cover off the case where it IS a missing file.

File: src/main/java/net/openhft/chronicle/queue/impl/single/TableDirectoryListing.java [hunk 2]
```diff
@@ -126,8 +126,10 @@ public void refresh(final boolean force) {
             if (!INITIAL_MAX_FILENAME.equals(maxFilename))
                 max = fileNameToCycleFunction.applyAsInt(maxFilename);
 
-            if (currentMin0 == min && currentMax0 == max)
+            if (currentMin0 == min && currentMax0 == max) {
+                modCount.addAtomicValue(1);
                 return;
+            }
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/queue/impl/single/TableDirectoryListing.java:132]: If someone did a force refresh, even if the min and max cycles didn't change, we should bump the modCount to trigger a rebuild of the cycle tree. This allows us to move past missing files.

File: src/test/java/net/openhft/chronicle/queue/impl/single/RollCycleTest.java [hunk 3]
```diff
@@ -289,7 +289,7 @@ public void newRollCycleIgnored2() throws InterruptedException {
                                 "\"3\"\n" +
                                 "...\n" +
                                 "# 130660 bytes remaining\n",
-                        queue.dump());
+                        queue.dump().replaceAll("listing.modCount: \\d+", "listing.modCount: 9"));
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/queue/impl/single/RollCycleTest.java:292]: This seems to change slightly due to concurrency/performance or something, just ignore modCount

File: src/test/java/net/openhft/chronicle/queue/TestDeleteQueueFile.java [hunk 4]
```diff
@@ -416,6 +416,17 @@ public void run() {
...
+        private DocumentContext readingDocumentWithRetries(ExcerptTailer excerptTailer) {
+            DocumentContext documentContext = null;
+            for (int i = 0; i < 2; i++) {
+                documentContext = excerptTailer.readingDocument();
+                if (documentContext.isPresent()) {
+                    break;
+                }
+            }
+            return documentContext;
+        }
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/queue/TestDeleteQueueFile.java:428]: We need to retry here, but that's OK, that's how people will use the API, the point is to prove with repeated calls to readingDocument you can progress through a queue with files being deleted from it.

File: src/main/java/net/openhft/chronicle/queue/impl/single/StoreTailer.java [hunk 5]
```diff
@@ -530,16 +530,15 @@ private long nextIndexWithNextAvailableCycle0(final int cycle) {
             nextIndex = nextIndexWithinFoundCycle(nextCycle);
         else
             try {
-                int nextCycle0 = this.cycle;
-                while (true) {
```
Comment (tgd) [inline src/main/java/net/openhft/chronicle/queue/impl/single/StoreTailer.java:534]: @nicktindall did this loop ever reach a second iteration or always breaks prior to that?

File: src/test/java/net/openhft/chronicle/queue/TestDeleteQueueFile.java [hunk 6]
```diff
@@ -416,6 +416,17 @@ public void run() {
             Jvm.startup().on(TestDeleteQueueFile.class, "Tailer thread terminated: " + direction);
         }
 
+        private DocumentContext readingDocumentWithRetries(ExcerptTailer excerptTailer) {
+            DocumentContext documentContext = null;
+            for (int i = 0; i < 2; i++) {
```
Comment (tgd) [inline src/test/java/net/openhft/chronicle/queue/TestDeleteQueueFile.java:421]: Is there any significance to the number chosen `2` here?

**Review by tgd — APPROVED** [review]
Thanks for sorting this Nick. I added a few questions which would be good to understand.

Would like a second pair of eyes from @JerryShea here too if poss.

File: src/main/java/net/openhft/chronicle/queue/impl/single/StoreTailer.java (hunk 5 above)
Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/queue/impl/single/StoreTailer.java:534]: The problem arose when this loop did make it to a second iteration, due to the first cycle being un-acquirable because of a bad header.

one such sequence of events was (two threads, cycle 3 is last cycle, with a bad header)

|tailer|appender|
|--------|------|
| | acquire cycle 3 for write|
|acquire cycle 3 for read|   |
|  | acquire 3 times out waiting for header|
|  | move invalid cycle 3 file|
|  | create/populate cycle 3 |
|  | create/populate cycle 4 |
|acquire 3 times out waiting for header | |
|assume 3 was deleted, skip to 4| | 

on that last row you just  skipped over the entries in (now valid) 3. It's an obscure sequence of events but can happen with very short (e.g. secondly) roll cycles, or in cases where the Appender is a replicator. Both of these things are true in UngracefulShutdownTest.

This change removes the (incorrect) assumption that `cycle(nextCycle0)` only returns false when the file doesn't exist.

File: src/test/java/net/openhft/chronicle/queue/TestDeleteQueueFile.java (hunk 6 above)
Comment (nicktindall) [reply src/test/java/net/openhft/chronicle/queue/TestDeleteQueueFile.java:421]: The first call to `readingDocument()` will return a not-present document context when a deleted cycle is encountered, but it will invalidate the cached cycle tree, so a subsequent call will rebuild that from disk and be able to skip forward to the next actually-present cycle. There's probably a small chance that it hits a deleted cycle twice in a row, but maybe we monitor that and see how likely it is.

**Comment by nicktindall** [comment]
> Thanks for sorting this Nick. I added a few questions which would be good to understand.
> 
> Would like a second pair of eyes from @JerryShea here too if poss.

Yes definitely, the more eyes the better on this.

**Comment by JerryShea** [comment]
> Thanks for sorting this Nick. I added a few questions which would be good to understand.
> 
> Would like a second pair of eyes from @JerryShea here too if poss.

LGTM but I raise your second pair of eyes request to @peter-lawrey

**Review by JerryShea — APPROVED** [review]

**Review by peter-lawrey — APPROVED** [review]
Great investigation
