### PR TITLE
Fix index arithmetic for -m in ChronicleReader, Fix #831

### LINKED ISSUE #831: ChronicleReader -i and -m
allow combine together of -i and -m i.e. display last X matching messages

### PR DESCRIPTION
**Pull request by nicktindall**

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/queue/reader/ChronicleReader.java [hunk 1]
```diff
@@ -272,12 +274,26 @@ private void moveToSpecifiedPosition(final ChronicleQueue ic, final ExcerptTaile
...
     }
 
+    private void moveToIndexNFromTheEnd(ExcerptTailer tailer, long numberOfEntriesFromEnd) {
+        tailer.direction(TailerDirection.BACKWARD).toEnd();
+        for (int i = 0; i < numberOfEntriesFromEnd - 1; i++) {
+            try (final DocumentContext documentContext = tailer.readingDocument()) {
+                if (!documentContext.isPresent()) {
+                    break;
+                }
+                System.out.println(documentContext.index());
```
Comment (JerryShea) [inline src/main/java/net/openhft/chronicle/queue/reader/ChronicleReader.java]: dangling System.out

File: src/test/java/net/openhft/chronicle/queue/internal/reader/ChronicleReaderTest.java [hunk 2]
```diff
@@ -319,16 +320,24 @@ public void shouldFilterByMultipleExclusionRegex() {
...
         basicReader().historyRecords(5).execute();
 
-        assertThat(capturedOutput.stream().
-                filter(msg -> !msg.startsWith("0x")).count(), is(5L));
+        assertEquals(5L, capturedOutput.stream().
+                filter(msg -> !msg.startsWith("0x")).count());
+    }
+
+    @Test
+    public void shouldCombineIncludeFilterAndMaxRecords() {
```
Comment (JerryShea) [inline src/test/java/net/openhft/chronicle/queue/internal/reader/ChronicleReaderTest.java:328]: nice

**Review by JerryShea — APPROVED** [review]
