### PR TITLE
Refresh directory listing and retry before failing nextCycle due to a missing store file

### LINKED ISSUE #948: Refresh directory listing and retry when a missing file is encountered during nextCycle
When a deleted file is encountered during a call to nextCycle, we throw an IllegalStateException. We could probably handle this more gracefully if we attempted to forcefully refresh the directory listing when this happens and retried once.

The exception is as follows, it could probably be fixed in `net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.nextCycle`
```
java.lang.IllegalStateException: Expected file to exist for cycle: 454664, file: queuefile.cq4. minCycle: 454705, maxCycle: 454705 Available files: [20211115-01LS.cq4]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue$StoreSupplier.nextCycle(SingleChronicleQueue.java:1226) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.WireStorePool.nextCycle(WireStorePool.java:66) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.SingleChronicleQueue.nextCycle(SingleChronicleQueue.java:568) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.nextIndexWithNextAvailableCycle(StoreTailer.java:516) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.endOfCycle(StoreTailer.java:341) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.next0(StoreTailer.java:314) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument0(StoreTailer.java:215) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:190) ~[chronicle-queue-5.22ea10.jar:?]
        at net.openhft.chronicle.queue.impl.single.StoreTailer.readingDocument(StoreTailer.java:134) ~[chronicle-queue-5.22ea10.jar:?]
```

### PR DESCRIPTION
**Pull request by nicktindall**
Fixes #948

I don't like this fix, and the fact we've implemented similar fixes in a few places makes me think there's a better place to catch this stuff, but the tests indicate it fixes the reported problem.

### CODE REVIEW

File: src/test/java/net/openhft/chronicle/queue/RollCycleDefaultingTest.java [hunk 1]
```diff
@@ -15,6 +16,11 @@ public void alias() {
         assertEquals(RollCycles.class, ObjectUtils.implementationToUse(RollCycle.class));
     }
 
+    @After
+    public void clearDefaultRollCycleProperty() {
+        System.clearProperty(QueueSystemProperties.DEFAULT_ROLL_CYCLE_PROPERTY);
+    }
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/queue/RollCycleDefaultingTest.java:22]: This was interfering with my test originally, I've since set the roll cycle explicitly, but felt like the right thing to do to clear it at the end.

File: src/test/java/net/openhft/chronicle/queue/TestDeleteQueueFile.java [hunk 2]
```diff
@@ -189,6 +191,49 @@ public void firstAndLastIndexAreRefreshedAfterForceRefreshInterval() throws IOEx
...
+        tailingThroughDeletedCyclesWillRefreshThenRetry(qwcd -> qwcd.queue);
+    }
+
+    @Test
+    public void tailingThroughDeletedCyclesWillRefreshThenRetry_ReadOnly() throws IOException {
+        tailingThroughDeletedCyclesWillRefreshThenRetry(qwcd -> SingleChronicleQueueBuilder.binary(qwcd.queue.fileAbsolutePath())
+                .rollCycle(RollCycles.FAST_DAILY)
+                .readOnly(true)
+                .build());
+    }
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/queue/TestDeleteQueueFile.java:205]: This manifested in different ways for read-only and writable queues, I'm not entirely sure why, but I think it was to do with the fact they use different `DirectoryListing` implementations

File: src/main/java/net/openhft/chronicle/queue/impl/single/StoreTailer.java [hunk 3]
```diff
@@ -500,6 +500,15 @@ private void inACycleFound(@NotNull final Bytes<?> bytes) {
     }
 
     private long nextIndexWithNextAvailableCycle(final int cycle) {
+        try {
+            return nextIndexWithNextAvailableCycle0(cycle);
+        } catch (MissingStoreFileException e) {
+            queue.refreshDirectoryListing();
+            return nextIndexWithNextAvailableCycle0(cycle);
+        }
+    }
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/queue/impl/single/StoreTailer.java:509]: This should only happen in scenarios where we used to throw an `IllegalStateException` or an `AssertionError` so it shouldn't affect the happy case, unless it impacts JIT in some mysterious way.

File: src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java [hunk 4]
```diff
@@ -1223,7 +1223,7 @@ public int nextCycle(int currentCycle, @NotNull TailerDirection direction) {
 
                 if (!fileFound) {
                     directoryListing.refresh(true);
-                    throw new IllegalStateException(
+                    throw new MissingStoreFileException(
```
Comment (JerryShea) [inline src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueue.java:1226]: nice

**Review by JerryShea — APPROVED** [review]
LGTM!

**Review by alamar — APPROVED** [review]

**Review by glukos — APPROVED** [review]
