### PR TITLE
Fixed fieldless queue by falling back to previous reading approach

### LINKED ISSUE #1232: Reading chronicle-queues of "fieldless_binary" wire type fails in some cases
When reading enums of certain lengths from a "fieldless_binary" queue, the method-reader fails on subsequent messages with the following error:
```
java.lang.IllegalStateException: Failed to read method name or ID
	at net.openhft.chronicle.queue.FieldlessTest$EntityListenerMethodReader.readOneCall(FieldlessTest$EntityListenerMethodReader.java:49)
	at net.openhft.chronicle.wire.AbstractGeneratedMethodReader.readOne0(AbstractGeneratedMethodReader.java:126)
	at net.openhft.chronicle.wire.AbstractGeneratedMethodReader.readOne(AbstractGeneratedMethodReader.java:233)
```

I have attached a junit test demonstrating the issue. [FieldlessTest.txt](https://github.com/OpenHFT/Chronicle-Queue/files/9879747/FieldlessTest.txt)

The test fails for both chronicle-queue versions 2.23.128 and 5.24ea0.
When using chronicle-queue version 4.16.4 it runs successfully.

### PR DESCRIPTION
**Pull request by alamar**
closes #1232

see a078d1aea7e424c7e2bbac33e3964d460fded22e

### CODE REVIEW

**Comment by alamar** [comment]
@peter-lawrey could you please take a look - perhaps we can leave only one if-branch somehow?

File: src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueStore.java [hunk 1]
```diff
@@ -77,13 +77,19 @@ private SingleChronicleQueueStore(@NotNull WireIn wire) {
...
-                if (MetaDataField.dataFormat.name().equals(fieldName))
-                    version = wire.getValueIn().int32();
-                else
-                    Jvm.warn().on(getClass(), "Unexpected field " + fieldName);
+            if (wire.isBinary() && ((BinaryWire)wire).fieldLess()) {
+                if (wire.bytes().readRemaining() > 0)
+                    version = wire.read(MetaDataField.dataFormat).int32();
+            } else {
+                final String fieldName = wire.readEvent(String.class);
+                if (fieldName != null)
```
Comment (peter-lawrey) [inline src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueStore.java]: // should cover fieldless and normal binary
if (fieldName == null || MetaDataField.dataFormat.name().equals(fieldName))

Comment (alamar) [reply src/main/java/net/openhft/chronicle/queue/impl/single/SingleChronicleQueueStore.java]: @peter-lawrey done - please take a look!

**Review by peter-lawrey — APPROVED** [review]
