### PR TITLE
Manage nested writing document calls counter

### LINKED ISSUE #896: StoreAppender can bypass write lock after an exception is thrown in writingDocument()
When a RuntimeException is thrown, the counter we use to keep track of nested calls to `StoreAppender.writingDocument()` can end up being out of sync leaving callers able to get a DocumentContext configured from a previous write. This can lead to queue corruption due to over-writing of already-written queue entries and concurrent writes occurring due to the write lock acquisition being bypassed.

### PR DESCRIPTION
**Pull request by nicktindall**
Fixes #896

Also use InterruptedRuntimeException instead of IllegalStateException and stop clearing interrupted flag in interrupted locks

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/queue/impl/single/TableStoreWriteLock.java [hunk 1]
```diff
@@ -64,8 +65,8 @@ public void lock() {
             long start = System.currentTimeMillis();
             while (!lock.compareAndSwapValue(UNLOCKED, PID)) {
                 // add a tiny delay
-                if (Thread.interrupted())
-                    throw new IllegalStateException("Interrupted for the lock file:" + path);
+                if (Thread.currentThread().isInterrupted())
```
Comment (JerryShea) [inline src/main/java/net/openhft/chronicle/queue/impl/single/TableStoreWriteLock.java:68]: should we `Thread.currentThread().interrupt(); ?`

**Review by JerryShea — APPROVED** [review]
fantastic

File: src/main/java/net/openhft/chronicle/queue/impl/single/TableStoreWriteLock.java (hunk 1 above)
Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/queue/impl/single/TableStoreWriteLock.java:68]: No
> The interrupted status of the thread is unaffected by this method.

From https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#isInterrupted--

Comment (JerryShea) [reply src/main/java/net/openhft/chronicle/queue/impl/single/TableStoreWriteLock.java:68]: Oh yes of course. It is friday afternoon after all ;)
